import asyncio
from sqlalchemy.ext.asyncio import AsyncSession
from app.database import SessionLocal
from app.models.contact import Contact

async def seed_contacts():
    async with SessionLocal() as db:
        # Check if contacts already exist
        from sqlalchemy import select
        result = await db.execute(select(Contact))
        if len(result.scalars().all()) > 0:
            print("Contacts already seeded.")
            return

        contacts = [
            Contact(
                name="Elon Musk",
                email="elon@tesla.com",
                phone="+1 (555) 123-4567",
                company="Tesla",
                last_meeting="2026-05-10",
                next_meeting="2026-06-01",
                lead_source="Inbound Demo Request",
                owner="Sarah Jenkins",
                status="proposal sent",
                industry="Automotive & Energy",
                company_size="10,000+",
                website="https://www.tesla.com",
                location="Austin, TX",
                domain="tesla.com",
                revenue_segment="Enterprise (>$10B)",
                assigned_rep="Sarah Jenkins",
                team="Global Enterprise",
                account_owner="Sarah Jenkins",
                manager="John Smith",
                ownership_transfer_history={"events": [{"date": "2026-05-01", "from": "System", "to": "Sarah Jenkins"}]},
                follow_up_status="proposal sent",
                next_action_date="2026-05-24",
                pipeline_stage="Proposal",
                lead_health="Healthy",
                sales_priority="High",
                source_tracking="Google Search Ad",
                campaign_attribution="Q2 Enterprise Campaign",
                conversion_score=95.0,
                engagement_score=92.0,
                booking_frequency="Bi-weekly",
                response_rate=98.0,
                lead_score=94.0,
                ai_intent_score=97.0,
                last_activity="Opened Proposal Email 2 hours ago",
                notes="Highly interested in calendar sync automation for Tesla Service Centers.",
                tags="enterprise,hot_lead,automotive",
                timeline_activity={"actions": [
                    {"date": "2026-05-10", "type": "meeting", "detail": "Attended 'Strategic Deep Dive'"},
                    {"date": "2026-05-01", "type": "booking", "detail": "Booked Strategic Product Demo"}
                ]}
            ),
            Contact(
                name="Tim Cook",
                email="tcook@apple.com",
                phone="+1 (555) 987-6543",
                company="Apple Inc.",
                last_meeting="2026-05-18",
                next_meeting="2026-06-10",
                lead_source="Cold Outreach",
                owner="Sarah Jenkins",
                status="demo completed",
                industry="Consumer Electronics",
                company_size="10,000+",
                website="https://www.apple.com",
                location="Cupertino, CA",
                domain="apple.com",
                revenue_segment="Enterprise (>$10B)",
                assigned_rep="Sarah Jenkins",
                team="Global Enterprise",
                account_owner="Sarah Jenkins",
                manager="John Smith",
                ownership_transfer_history={"events": []},
                follow_up_status="demo completed",
                next_action_date="2026-05-20",
                pipeline_stage="Qualification",
                lead_health="Healthy",
                sales_priority="High",
                source_tracking="LinkedIn InMail",
                campaign_attribution="Outbound Target 50",
                conversion_score=85.0,
                engagement_score=88.0,
                booking_frequency="Monthly",
                response_rate=85.0,
                lead_score=88.0,
                ai_intent_score=91.0,
                last_activity="Replied to scheduling follow-up",
                notes="Reviewing for developer onboarding operations scaling.",
                tags="enterprise,warm_lead,hardware",
                timeline_activity={"actions": [
                    {"date": "2026-05-18", "type": "meeting", "detail": "Attended 'Product Demo'"}
                ]}
            ),
            Contact(
                name="Sundar Pichai",
                email="sundar@google.com",
                phone="+1 (555) 246-8101",
                company="Google",
                last_meeting=None,
                next_meeting="2026-06-02",
                lead_source="Inbound Demo Request",
                owner="Sarah Jenkins",
                status="follow-up pending",
                industry="Software & Internet",
                company_size="10,000+",
                website="https://www.google.com",
                location="Mountain View, CA",
                domain="google.com",
                revenue_segment="Enterprise (>$10B)",
                assigned_rep="Sarah Jenkins",
                team="Global Enterprise",
                account_owner="Sarah Jenkins",
                manager="John Smith",
                ownership_transfer_history={"events": []},
                follow_up_status="follow-up pending",
                next_action_date="2026-05-22",
                pipeline_stage="Discovery",
                lead_health="Healthy",
                sales_priority="High",
                source_tracking="Direct Website Visit",
                campaign_attribution="Organic Search",
                conversion_score=78.0,
                engagement_score=80.0,
                booking_frequency="One-time",
                response_rate=90.0,
                lead_score=82.0,
                ai_intent_score=85.0,
                last_activity="Registered for Strategic Session",
                notes="Evaluating Google Calendar Enterprise Sync API latencies.",
                tags="enterprise,cloud",
                timeline_activity={"actions": [
                    {"date": "2026-05-19", "type": "booking", "detail": "Booked Strategic Session"}
                ]}
            ),
            Contact(
                name="Richard Branson",
                email="richard@virgin.com",
                phone="+44 20 7229 4000",
                company="Virgin Group",
                last_meeting="2026-03-15",
                next_meeting=None,
                lead_source="Partner Referral",
                owner="Sarah Jenkins",
                status="inactive 30 days",
                industry="Conglomerate",
                company_size="1,000-5,000",
                website="https://www.virgin.com",
                location="London, UK",
                domain="virgin.com",
                revenue_segment="Mid-Market ($100M-$1B)",
                assigned_rep="Sarah Jenkins",
                team="UK Sales",
                account_owner="Sarah Jenkins",
                manager="John Smith",
                ownership_transfer_history={"events": []},
                follow_up_status="contacted",
                next_action_date="2026-06-01",
                pipeline_stage="Nurture",
                lead_health="Warning",
                sales_priority="Medium",
                source_tracking="Partner Network",
                campaign_attribution="Affiliate Program",
                conversion_score=45.0,
                engagement_score=35.0,
                booking_frequency="Rarely",
                response_rate=50.0,
                lead_score=40.0,
                ai_intent_score=30.0,
                last_activity="Email opened 28 days ago",
                notes="Interested in scheduling workflows for aviation crew round-robins.",
                tags="travel,nurture",
                timeline_activity={"actions": [
                    {"date": "2026-03-15", "type": "meeting", "detail": "Attended introductory sync"}
                ]}
            ),
            Contact(
                name="Jensen Huang",
                email="jensen@nvidia.com",
                phone="+1 (555) 765-4321",
                company="NVIDIA",
                last_meeting=None,
                next_meeting=None,
                lead_source="Events",
                owner="Sarah Jenkins",
                status="New",
                industry="Semiconductors & AI",
                company_size="10,000+",
                website="https://www.nvidia.com",
                location="Santa Clara, CA",
                domain="nvidia.com",
                revenue_segment="Enterprise (>$10B)",
                assigned_rep="Sarah Jenkins",
                team="Global Enterprise",
                account_owner="Sarah Jenkins",
                manager="John Smith",
                ownership_transfer_history={"events": []},
                follow_up_status="follow-up pending",
                next_action_date="2026-05-20",
                pipeline_stage="Discovery",
                lead_health="Healthy",
                sales_priority="High",
                source_tracking="GTC Event",
                campaign_attribution="GTC 2026 Event Scan",
                conversion_score=92.0,
                engagement_score=90.0,
                booking_frequency="Frequent",
                response_rate=95.0,
                lead_score=93.0,
                ai_intent_score=96.0,
                last_activity="Attended event presentation",
                notes="Expressed key interest in AI agent qualification nodes.",
                tags="new,hot_lead,ai",
                timeline_activity={"actions": [
                    {"date": "2026-05-18", "type": "event", "detail": "Scanned badge at GTC Booth"}
                ]}
            ),
            Contact(
                name="Mark Zuckerberg",
                email="zuck@meta.com",
                phone="+1 (555) 111-2222",
                company="Meta",
                last_meeting="2026-05-02",
                next_meeting=None,
                lead_source="Inbound Demo Request",
                owner="Sarah Jenkins",
                status="closed lost",
                industry="Software & Internet",
                company_size="10,000+",
                website="https://www.meta.com",
                location="Menlo Park, CA",
                domain="meta.com",
                revenue_segment="Enterprise (>$10B)",
                assigned_rep="Sarah Jenkins",
                team="Global Enterprise",
                account_owner="Sarah Jenkins",
                manager="John Smith",
                ownership_transfer_history={"events": []},
                follow_up_status="closed lost",
                next_action_date=None,
                pipeline_stage="Closed Lost",
                lead_health="Critical",
                sales_priority="Low",
                source_tracking="Meta Ads",
                campaign_attribution="Enterprise Retargeting",
                conversion_score=20.0,
                engagement_score=15.0,
                booking_frequency="Rarely",
                response_rate=10.0,
                lead_score=15.0,
                ai_intent_score=5.0,
                last_activity="Declined calendar invitation",
                notes="Replaced internal scheduling with proprietary WhatsApp Business automations.",
                tags="lost",
                timeline_activity={"actions": [
                    {"date": "2026-05-02", "type": "meeting", "detail": "Declined meeting proposal"}
                ]}
            ),
            Contact(
                name="Satya Nadella",
                email="satya@microsoft.com",
                phone="+1 (555) 333-4444",
                company="Microsoft",
                last_meeting="2026-05-15",
                next_meeting=None,
                lead_source="Direct Website Visit",
                owner="Sarah Jenkins",
                status="closed won",
                industry="Software & Internet",
                company_size="10,000+",
                website="https://www.microsoft.com",
                location="Redmond, WA",
                domain="microsoft.com",
                revenue_segment="Enterprise (>$10B)",
                assigned_rep="Sarah Jenkins",
                team="Global Enterprise",
                account_owner="Sarah Jenkins",
                manager="John Smith",
                ownership_transfer_history={"events": []},
                follow_up_status="closed won",
                next_action_date=None,
                pipeline_stage="Closed Won",
                lead_health="Healthy",
                sales_priority="High",
                source_tracking="Microsoft Partnerships",
                campaign_attribution="Strategic Ecosystem Alliance",
                conversion_score=99.0,
                engagement_score=99.0,
                booking_frequency="Weekly",
                response_rate=100.0,
                lead_score=99.0,
                ai_intent_score=99.0,
                last_activity="Signed Master Services Agreement",
                notes="Onboarding completed for Microsoft Teams dynamic boardroom modules.",
                tags="customer,enterprise,teams",
                timeline_activity={"actions": [
                    {"date": "2026-05-15", "type": "contract", "detail": "Signed contract for 1,000 seats"}
                ]}
            )
        ]
        db.add_all(contacts)
        await db.commit()
        print("Successfully seeded GTM enterprise contacts!")

if __name__ == "__main__":
    asyncio.run(seed_contacts())
